package flower;

public enum NameFlower {
    LILY_MARTAGON,
    PEONY_EUVROPEAN,
    LILY_ASIATIC,
    PEONY_JAPANESE,
    ROSE_AMSTERDAM,
    ROSE_ENGLISH,
    CHRYSANTHEMUM_BACARDI,
    CHRYSANTHEMUM_REAGAN,
    VIOLET_PANCIES,
    VIOLET_STAR

}
